### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by hdghg** [hdghg/jate#10]
08:28:11.011Z [jate-pool-4] ERROR r.h.j.u.TelegramUpdatesConsumer - Exception 1 in updatesConsumer
    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "migrate_to_chat_id" (class ru.hdghg.tg.model.TelegramMessage)[Source: {"ok":true,"result":[{"update_id":1114037,
"message":{"message_id":5667,"from":{"id":118979550,"first_name":"hpswgprk","username":"hpswgprk"},"chat":{"id":-160346991,"title":"s@ | \u043a\u0442\u043e \u0436\u0435 \u0441\u0435\u0433\u043e\u0434\u043d\u044f \
u0441\u043e\u0441\u043d\u0443\u043b?","type":"group","all_members_are_administrators":false},"date":1486715291,"migrate_to_chat_id":-1001103425247}}]}; line: 2, column: 360] (through reference chain: ru.hdghg.tg.m
odel.ResultUpdate["result"]->java.util.ArrayList[0]->ru.hdghg.tg.model.Update["message"]->ru.hdghg.tg.model.TelegramMessage["migrate_to_chat_id"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
        at ru.hdghg.tg.api.HighLevel.getUpdate(HighLevel.java:76)
        at ru.hdghg.jate.updates.TelegramUpdatesConsumer.run(TelegramUpdatesConsumer.java:35)

**Comment by hdghg** [comment]
https://github.com/hdghg/jate/commit/f075c35ee9a037a40eb83c463b6a8c72b7281aea
