### ISSUE TITLE
Migration error 2

### ISSUE THREAD

**Issue by hdghg** [hdghg/jate#11]
08:28:11.011Z [jate-pool-4] ERROR r.h.j.u.TelegramUpdatesConsumer - Exception 2 in updatesConsumer
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "parameters" (class ru.hdghg.tg.model.ResultMessage), not marked as ignorable (4 known properties: "ok", "result", "description", "error_code"])
 at [Source: {"ok":false,"error_code":400,"description":"Bad Request: group chat was migrated to a supergroup chat","parameters":{"migrate_to_chat_id":-1001103425247}}; line: 1, column: 118] (through reference chain: ru.hdghg.tg.model.ResultMessage["parameters"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
        at ru.hdghg.tg.api.HighLevel.sendMessage(HighLevel.java:29)
        at ru.hdghg.jate.updates.TelegramUpdatesConsumer.run(TelegramUpdatesConsumer.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hdghg** [comment]
https://github.com/hdghg/jate/commit/f075c35ee9a037a40eb83c463b6a8c72b7281aea
